# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
                ('reps', models.PositiveIntegerField(verbose_name='repetitions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='wglog.Training', verbose_name='training'),
        ),
    ]
