# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 05:08
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models.expressions import F
import django.db.models.deletion


def name_to_temp_name(apps, shema_editor):
    Training = apps.get_model('wglog', 'Training')
    Training.objects.all().update(temp_name=F('name'))


def extract_trainings_names(apps, shema_editor):
    """name must be altered to ForeignKey"""
    Training = apps.get_model('wglog', 'Training')
    TrainingName = apps.get_model('wglog', 'TrainingName')

    for training in Training.objects.all():
        training_name = TrainingName.objects.get_or_create(text=training.temp_name)[0]
        training.name = training_name
        training.save()


class Migration(migrations.Migration):
    """Irreversible migration"""

    dependencies = [
        ('wglog', '0003_add_training_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='temp_name',
            field=models.CharField(max_length=250, verbose_name='name', null=True)
        ),
        migrations.RunPython(name_to_temp_name),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='wglog.TrainingName',
                verbose_name='name',
                null=True
            ),
        ),
        migrations.RunPython(extract_trainings_names),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='wglog.TrainingName',
                verbose_name='name',
                null=False
            ),
        ),
        migrations.RemoveField(
            model_name='training',
            name='temp_name'
        )
    ]
