# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wglog', '0004_extract_training_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='created_at',
        ),
        migrations.AddField(
            model_name='set',
            name='started_at',
            field=models.DateTimeField(null=True, verbose_name='started at'),
        ),
        migrations.AddField(
            model_name='set',
            name='stopped_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='stopped at'),
        ),
    ]
