# Generated by Django 2.0 on 2017-12-26 11:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import wglog.models


class Migration(migrations.Migration):

    dependencies = [
        ('wglog', '0005_set_start_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=wglog.models.UserSettings.default),
        ),
    ]
