# Generated by Django 2.0 on 2018-01-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wglog', '0006_add_user_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='wglog.Training', verbose_name='training'),
        ),
    ]
